### ISSUE TITLE
Error log: settings page

### ISSUE THREAD

**Issue by d4ywalkr** [palasthotel/blockX#28]
```
thrown in /home/wp/disk/wordpress/wp-content/plugins/blockx/classes/Settings.php on line 192
--
#8 {main}
#7 /home/wp/disk/wordpress/wp-admin/options-general.php(10): require_once('...')
#6 /home/wp/disk/wordpress/wp-admin/admin.php(259): do_action()
#5 /home/wp/disk/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#3 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(310): Palasthotel\WordPress\BlockX\Settings->render_settings_form()
#2 /home/wp/disk/wordpress/wp-content/plugins/blockx/classes/Settings.php(147): do_settings_sections()
#1 /home/wp/disk/wordpress/wp-admin/includes/template.php(1778): do_settings_fields()
#0 /home/wp/disk/wordpress/wp-admin/includes/template.php(1824): Palasthotel\WordPress\BlockX\Settings->render_regenerate_assets()
Stack trace:
[26-Oct-2023 13:22:22 UTC] PHP Fatal error: Uncaught Error: Cannot access private property Palasthotel\WordPress\BlockX\BlockAssetsGenerator::$paths in /home/wp/disk/wordpress/wp-content/plugins/blockx/classes/Settings.php:192
thrown in /home/wp/disk/wordpress/wp-content/plugins/blockx/classes/Settings.php on line 192
#8 {main}
#7 /home/wp/disk/wordpress/wp-admin/options-general.php(10): require_once('...')
#6 /home/wp/disk/wordpress/wp-admin/admin.php(259): do_action()
#5 /home/wp/disk/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#3 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(310): Palasthotel\WordPress\BlockX\Settings->render_settings_form()
#2 /home/wp/disk/wordpress/wp-content/plugins/blockx/classes/Settings.php(147): do_settings_sections()
#1 /home/wp/disk/wordpress/wp-admin/includes/template.php(1778): do_settings_fields()
#0 /home/wp/disk/wordpress/wp-admin/includes/template.php(1824): Palasthotel\WordPress\BlockX\Settings->render_regenerate_assets()
Stack trace:
[26-Oct-2023 13:22:16 UTC] PHP Fatal error: Uncaught Error: Cannot access private property Palasthotel\WordPress\BlockX\BlockAssetsGenerator::$paths in /home/wp/disk/wordpress/wp-content/plugins/blockx/classes/Settings.php:192
thrown in /home/wp/disk/wordpress/wp-content/plugins/blockx/classes/Settings.php on line 192
#8 {main}
#7 /home/wp/disk/wordpress/wp-admin/options-general.php(10): require_once('...')
#6 /home/wp/disk/wordpress/wp-admin/admin.php(259): do_action()
#5 /home/wp/disk/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#3 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(310): Palasthotel\WordPress\BlockX\Settings->render_settings_form()
#2 /home/wp/disk/wordpress/wp-content/plugins/blockx/classes/Settings.php(147): do_settings_sections()
#1 /home/wp/disk/wordpress/wp-admin/includes/template.php(1778): do_settings_fields()
#0 /home/wp/disk/wordpress/wp-admin/includes/template.php(1824): Palasthotel\WordPress\BlockX\Settings->render_regenerate_assets()
Stack trace:
[26-Oct-2023 13:22:07 UTC] PHP Fatal error: Uncaught Error: Cannot access private property Palasthotel\WordPress\BlockX\BlockAssetsGenerator::$paths in /home/wp/disk/wordpress/wp-content/plugins/blockx/classes/Settings.php:192
thrown in /home/wp/disk/wordpress/wp-content/plugins/blockx/classes/Settings.php on line 192
#8 {main}
#7 /home/wp/disk/wordpress/wp-admin/options-general.php(10): require_once('...')
#6 /home/wp/disk/wordpress/wp-admin/admin.php(259): do_action()
#5 /home/wp/disk/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#3 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(310): Palasthotel\WordPress\BlockX\Settings->render_settings_form()
#2 /home/wp/disk/wordpress/wp-content/plugins/blockx/classes/Settings.php(147): do_settings_sections()
#1 /home/wp/disk/wordpress/wp-admin/includes/template.php(1778): do_settings_fields()


```

**Comment by EdwardBock** [comment]
Is fixed with version 1.9.2
